### ISSUE TITLE
Cannot build with D compiler

### ISSUE THREAD

**Issue by AM2petterk** [CyberShadow/MyWormNET2#1]
Hi,

```
rdmd --build-only mywormnet2
http.d(70): Error: cannot implicitly convert expression (decodeUrlParameters(pathStr[cast(ulong)(p + 1L)..__dollar])) of type MultiAA!(string, string) to string[string]
http.d(81): Error: no property 'localAddress' for type 'ae.net.asockets.IConnection'
```

**Comment by CyberShadow** [comment]
The code in this repository is no longer buildable with ae `master`. I updated the instructions in the README.

**Comment by deed02392** [comment]
I too am having troubles building with the latest instructions. Another library conflict? 

I am using MyWormNET2 clone of master and ae from the archive link given in the README.md:

```
ae/utils/array.d(70): Error: function ae.utils.array.memcmp (const(ubyte[]) a, const(ubyte[]) b) is not callable using argument types (const(ubyte)*, const(ubyte)*, ulong)
```
Just tried rebuilding with the exact command line arguments given (i.e. not using `git clone`) and it's the same error unfortunately.

**Update:**

Managed to fix it with an explicit reference to the memcmp function that is supposed to be being wrapped.

`core.stdc.string.memcmp`

**Comment by deed02392** [comment]
It still refuses to run. Perhaps these Deprecations are too serious:

```
# rdmd mywormnet2 || echo "Failed :(" $?
ae/sys/data.d(136): Deprecation: constructor ae.sys.data.Data.this all parameters have default arguments, but structs cannot have default constructors.
ae/sys/cmd.d(168): Deprecation: catch statement without an exception specification is deprecated; use catch(Throwable) for old behavior
ae/utils/zlib.d(184): Deprecation: cannot subtract pointers to different types: ubyte* and const(void)*.
ae/utils/zlib.d(184): Deprecation: cannot subtract pointers to different types: ubyte* and const(void)*.
ae/sys/dataio.d(144): Deprecation: std.file.core is not visible from module dataio
ae/sys/dataio.d(144): Deprecation: package core.stdc is not accessible here
ae/sys/dataio.d(144): Deprecation: module core.stdc.stdio is not accessible here, perhaps add 'static import core.stdc.stdio;'
ae/utils/time.d(815): Deprecation: module std.conv is not accessible here, perhaps add 'static import std.conv;'
Failed :( 247
```

**Comment by CyberShadow** [comment]
Should be fixed now. Follow the README instructions again.

**Comment by deed02392** [comment]
Are you a machine? Did you just fix this and push the solution to the dub package repo too?

**Comment by CyberShadow** [comment]
What's the dub package repo problem?

**Comment by deed02392** [comment]
No problem, I am just amazed how quickly you did all that. :-) Sorry for the confusion.

**Comment by deed02392** [comment]
OK, it looks like I still cannot get it to run. I tried with dub:

```
# dub fetch mywormnet2
# dub list
Packages present in the system and known to dub:
  mywormnet2 1.0.0: /root/.dub/packages/mywormnet2-1.0.0/mywormnet2/
  ae 0.0.2097: /root/.dub/packages/ae-0.0.2097/ae/
  ae:sqlite 0.0.2097: /root/.dub/packages/ae-0.0.2097/ae/
  ae:openssl 0.0.2097: /root/.dub/packages/ae-0.0.2097/ae/
  ae:sdl2 0.0.2097: /root/.dub/packages/ae-0.0.2097/ae/
  ae:windows 0.0.2097: /root/.dub/packages/ae-0.0.2097/ae/
  ae:app-main-posix 0.0.2097: /root/.dub/packages/ae-0.0.2097/ae/
  ae:app-main-windows 0.0.2097: /root/.dub/packages/ae-0.0.2097/ae/
  ae:app-main 0.0.2097: /root/.dub/packages/ae-0.0.2097/ae/
# cd .dub/packages/mywormnet2-1.0.0/mywormnet2/
# cp ~george/mywormnet2.ini ~george/motd.txt ~george/news.html .
# dub run mywormnet2
Building package mywormnet2 in /root/.dub/packages/mywormnet2-1.0.0/mywormnet2/
Fetching ae 0.0.2097 (getting selected version)...
Performing "debug" build using dmd for x86_64.
mywormnet2 1.0.0: building configuration "application"...
Killed
dmd failed with exit code 137.
```

and with `git clone --recursive`:

```
root@mywormnet2:~/MyWormNET2# rdmd mywormnet2
root@mywormnet2:~/MyWormNET2# echo $?
247
```

This is the same exit code as before. At least I do not get any deprecation warnings now.

**Update**
I discovered that code 137 relates to an out of memory issue when compiling. My VM for WormNET only had 512 MiB RAM, so I increased this to 2 GiB and the program compiled.

**Comment by CyberShadow** [comment]
👍

Yes, D compilers need a lot of RAM generally.
